const VERSION='1.1.2';
const domains=[
 {id:'fund',icon:'🧱',title:'Network Fundamentals',desc:'Learn what networks are, how data moves, Ethernet, IPv4/IPv6 and subnetting.'},
 {id:'access',icon:'🔀',title:'Network Access',desc:'Switching, VLANs, trunks, STP, EtherChannel and wireless access.'},
 {id:'routing',icon:'🧭',title:'IP Connectivity',desc:'Routing tables, static routes, OSPF and path selection.'},
 {id:'services',icon:'🛠️',title:'IP Services',desc:'DHCP, DNS, NAT, NTP, QoS, SNMP, syslog and SSH.'},
 {id:'security',icon:'🛡️',title:'Security Fundamentals',desc:'Threats, hardening, ACLs, port security, AAA, VPN and wireless security.'},
 {id:'auto',icon:'🤖',title:'Automation & Programmability',desc:'Controllers, APIs, JSON, automation and modern network operations.'}
];
const lessons=[
 {id:'f1',domain:'fund',title:'What Is a Network?',mins:12,lab:null,body:`
   <p>You already use networks every day. When your phone opens a website, it must get data from another computer. A <b>network</b> is simply a group of devices that can exchange information.</p>
   <div class="analogy"><b>Think of a network like a delivery system.</b> End devices are houses, switches are local sorting depots, routers choose roads between towns, and an IP address tells the delivery system where a packet needs to go.</div>
   <h3>The four jobs to remember</h3><ul><li><b>Hosts</b> create and consume data: laptops, phones, servers, cameras.</li><li><b>Switches</b> move Ethernet frames inside a LAN.</li><li><b>Routers</b> move IP packets between different networks.</li><li><b>Media</b> carries signals: copper, fiber, or radio.</li></ul>
   <div class="concept-box"><b>Exam language:</b> A LAN normally covers a local area. A WAN connects networks across larger geographic areas. The Internet is a network of networks.</div>`,q:{q:'Which device normally forwards traffic between different IP networks?',opts:['Switch','Router','Wireless client','Patch panel'],a:1,e:'A router makes Layer 3 forwarding decisions between IP networks.'}},
 {id:'f2',domain:'fund',title:'How Data Travels: OSI & TCP/IP',mins:18,body:`<p>Networking becomes easier when you stop seeing “the network” as one giant thing. Models split communication into jobs.</p><h3>A beginner-friendly mental model</h3><ol><li><b>Application:</b> what the user wants — web, email, DNS.</li><li><b>Transport:</b> conversation handling — TCP or UDP.</li><li><b>Internet/Network:</b> IP addressing and routing.</li><li><b>Link:</b> Ethernet/Wi-Fi delivery on the local network.</li><li><b>Physical:</b> bits as electrical, optical or radio signals.</li></ol><div class="analogy"><b>Encapsulation</b> is like putting a letter in an envelope, then a courier bag, then a delivery vehicle. Each layer adds information needed for its job.</div><h3>PDU names worth learning</h3><p>Application data → TCP <b>segment</b> / UDP datagram → IP <b>packet</b> → Ethernet <b>frame</b> → <b>bits</b>.</p>`,q:{q:'At which OSI layer does IP routing occur?',opts:['Layer 1','Layer 2','Layer 3','Layer 7'],a:2,e:'IP belongs to the Network layer, Layer 3.'}},
 {id:'f3',domain:'fund',title:'Ethernet, MAC Addresses & Switching',mins:22,lab:'l1',body:`<p>A switch learns where devices are by reading source MAC addresses. It builds a <b>MAC address table</b>, then forwards known unicast frames only toward the correct port.</p><h3>What a switch does with a frame</h3><ul><li>Learn the <b>source MAC</b> on the incoming port.</li><li>Look up the <b>destination MAC</b>.</li><li>If known, forward out one port.</li><li>If unknown, flood within the VLAN except the incoming port.</li></ul><div class="concept-box"><b>Important:</b> a MAC address is Layer 2; an IPv4/IPv6 address is Layer 3. ARP helps an IPv4 host discover the MAC address associated with a local IPv4 address.</div>`,q:{q:'A switch receives a frame for a destination MAC it has not learned. What does it normally do?',opts:['Drops it immediately','Sends it to the default gateway only','Floods it within the VLAN','Converts it to a broadcast IP packet'],a:2,e:'Unknown unicast frames are flooded in the local VLAN, except back out the receiving port.'}},
 {id:'f4',domain:'fund',title:'IPv4 Addressing Without the Pain',mins:28,body:`<p>An IPv4 address is 32 bits. Humans write it as four decimal octets, such as <code>192.168.10.25</code>. A prefix such as <code>/24</code> says how many left-most bits describe the network.</p><div class="analogy"><b>Street analogy:</b> the network portion is the street name; the host portion is the house number. Routers care about getting you to the right street.</div><h3>Three private IPv4 ranges</h3><p><code>10.0.0.0/8</code>, <code>172.16.0.0/12</code>, and <code>192.168.0.0/16</code>. These are not routed globally on the public Internet.</p><h3>For a /24</h3><p><code>192.168.10.0</code> is the network, usable hosts are normally <code>.1</code> through <code>.254</code>, and <code>.255</code> is the broadcast address.</p>`,q:{q:'Which address is private IPv4 space?',opts:['8.8.8.8','172.20.5.10','200.1.1.1','1.1.1.1'],a:1,e:'172.16.0.0 through 172.31.255.255 is private space.'}},
 {id:'f5',domain:'fund',title:'Subnetting: Learn the Pattern',mins:35,body:`<p>Subnetting means borrowing host bits to create more, smaller networks. Do not begin by memorizing every mask. Learn the pattern.</p><div class="concept-box"><b>Useful /24 ladder:</b> /25 = 128 addresses, /26 = 64, /27 = 32, /28 = 16, /29 = 8, /30 = 4. Traditional usable-host count is total addresses minus 2.</div><h3>Example: 192.168.1.0/26</h3><p>Block size is 64. Subnets start at .0, .64, .128, .192. The first subnet spans .0–.63; network=.0, broadcast=.63, traditional usable hosts=.1–.62.</p><div class="warning">CCNA success requires doing subnetting repeatedly, not just recognizing answers. Use paper until the pattern is automatic.</div>`,q:{q:'How many total IPv4 addresses are in a /27 block?',opts:['16','32','64','128'],a:1,e:'A /27 leaves 5 host bits: 2^5 = 32 total addresses.'}},
 {id:'f6',domain:'fund',title:'TCP, UDP & Common Applications',mins:18,body:`<p>TCP is connection-oriented and provides sequencing, acknowledgements and retransmission. UDP has lower overhead and does not provide those reliability mechanisms itself.</p><h3>Common examples</h3><p>HTTP/HTTPS usually use TCP; SSH uses TCP; DNS commonly uses UDP for ordinary queries but can use TCP; DHCP uses UDP. Real-time applications often favor UDP because waiting for retransmissions can be worse than losing a small amount of data.</p>`,q:{q:'Which transport protocol provides acknowledgements and retransmission?',opts:['IP','TCP','UDP','ARP'],a:1,e:'TCP provides reliable, ordered transport mechanisms.'}},
 {id:'f7',domain:'fund',title:'IPv6 Essentials',mins:22,body:`<p>IPv6 uses 128-bit addresses written in hexadecimal. It dramatically expands address space and changes several behaviors you learned in IPv4.</p><h3>Know these types</h3><ul><li><b>Global unicast:</b> globally routable.</li><li><b>Link-local:</b> begins with FE80::/10 and works on the local link.</li><li><b>Multicast:</b> one-to-many group delivery.</li><li><b>Anycast:</b> same address on multiple nodes; routing reaches a nearest instance.</li></ul><p>IPv6 does not use broadcast the way IPv4 does.</p>`,q:{q:'Which prefix identifies IPv6 link-local addresses?',opts:['2000::/3','FE80::/10','FF00::/8','FC00::/7'],a:1,e:'IPv6 link-local addresses use FE80::/10.'}},
 {id:'a1',domain:'access',title:'Cisco IOS & Your First Switch',mins:22,lab:'l1',body:`<p>Cisco IOS uses modes. You begin in user EXEC (<code>&gt;</code>), enter privileged EXEC with <code>enable</code>, then global configuration with <code>configure terminal</code>.</p><h3>Your first safe sequence</h3><p><code>enable</code> → <code>configure terminal</code> → <code>hostname SW1</code> → <code>end</code> → <code>show running-config</code>.</p><div class="analogy">CLI modes are like rooms in a workshop. Some tools are only available in certain rooms. The prompt tells you where you are.</div>`,q:{q:'Which command enters privileged EXEC mode from user EXEC?',opts:['configure terminal','enable','login','show run'],a:1,e:'enable changes the prompt from > to #.'}},
 {id:'a2',domain:'access',title:'VLANs: One Switch, Multiple LANs',mins:26,lab:'l2',body:`<p>A VLAN creates a separate Layer 2 broadcast domain. Devices in different VLANs need Layer 3 routing to communicate.</p><h3>Access vs trunk</h3><p>An <b>access port</b> normally carries one data VLAN. A <b>trunk</b> carries traffic for multiple VLANs using IEEE 802.1Q tagging.</p><div class="concept-box">Common verification: <code>show vlan brief</code> and <code>show interfaces trunk</code>.</div>`,q:{q:'What is the main purpose of an 802.1Q trunk?',opts:['Encrypt switch traffic','Carry multiple VLANs over one link','Assign IP addresses','Prevent all loops'],a:1,e:'802.1Q tags frames so multiple VLANs can cross one physical link.'}},
 {id:'a3',domain:'access',title:'STP: Stopping Switching Loops',mins:25,body:`<p>Redundant Layer 2 links are useful, but Ethernet frames have no TTL. A loop can create broadcast storms and MAC table instability. Spanning Tree Protocol creates a loop-free logical topology.</p><h3>Core idea</h3><p>STP elects a <b>root bridge</b>, calculates best paths toward it, and places redundant ports into non-forwarding roles/states so the topology has no active loop.</p>`,q:{q:'Why is STP needed in a redundant switched network?',opts:['To assign VLAN IDs','To prevent Layer 2 loops','To encrypt trunks','To advertise IP routes'],a:1,e:'STP prevents Layer 2 forwarding loops while allowing physical redundancy.'}},
 {id:'a4',domain:'access',title:'EtherChannel: More Bandwidth, One Logical Link',mins:18,body:`<p>EtherChannel bundles compatible physical Ethernet links into one logical port-channel. STP sees the bundle as a single logical connection.</p><p>LACP is the standards-based negotiation protocol. Member interfaces need compatible settings such as speed, duplex, access/trunk mode, and VLAN parameters.</p>`,q:{q:'Which standards-based protocol negotiates EtherChannel?',opts:['OSPF','LACP','HSRP','DTP'],a:1,e:'LACP is the standards-based EtherChannel negotiation protocol.'}},
 {id:'r1',domain:'routing',title:'Routing: How a Router Thinks',mins:25,lab:'l3',body:`<p>A router checks the destination IP address against its routing table and chooses the most specific matching route — the <b>longest prefix match</b>.</p><h3>Route sources</h3><ul><li>Connected routes come from active configured interfaces.</li><li>Static routes are manually configured.</li><li>Dynamic routing protocols such as OSPF learn routes automatically.</li></ul><p>A default route <code>0.0.0.0/0</code> is the catch-all when no more-specific route matches.</p>`,q:{q:'A router has 10.0.0.0/8 and 10.1.2.0/24. Which route matches destination 10.1.2.55?',opts:['10.0.0.0/8','10.1.2.0/24','Both equally','Neither'],a:1,e:'The /24 is more specific, so longest-prefix match chooses it.'}},
 {id:'r2',domain:'routing',title:'Static & Default Routes',mins:25,lab:'l3',body:`<p>A common IPv4 static route format is <code>ip route NETWORK MASK NEXT-HOP</code>. A default route is <code>ip route 0.0.0.0 0.0.0.0 NEXT-HOP</code>.</p><div class="warning">A configured static route is not automatically a good route. Always verify reachability, next-hop correctness, and the routing table.</div>`,q:{q:'What does 0.0.0.0/0 represent?',opts:['Loopback','Default route','Broadcast route','Host route'],a:1,e:'0.0.0.0/0 matches any IPv4 destination not matched by a more-specific route.'}},
 {id:'r3',domain:'routing',title:'OSPF: Dynamic Routing for Real Networks',mins:32,lab:'l4',body:`<p>OSPF is a link-state interior gateway protocol. Routers form neighbor relationships, exchange topology information, and calculate shortest paths using cost.</p><h3>CCNA focus</h3><p>Understand neighbor requirements, router ID, single-area OSPF, designated router concepts on multiaccess networks, and verification with commands such as <code>show ip ospf neighbor</code> and <code>show ip route ospf</code>.</p>`,q:{q:'What type of routing protocol is OSPF?',opts:['Distance-vector only','Link-state','Exterior gateway','Layer 2 discovery'],a:1,e:'OSPF is a link-state IGP.'}},
 {id:'s1',domain:'services',title:'DHCP, DNS & NTP',mins:24,body:`<p>Three services solve very different problems. <b>DHCP</b> leases IP configuration, <b>DNS</b> resolves names to addresses, and <b>NTP</b> synchronizes clocks.</p><h3>DHCP DORA</h3><p>Discover → Offer → Request → Acknowledge. A DHCP relay forwards client DHCP messages between subnets when the server is elsewhere.</p>`,q:{q:'Which service translates host names into IP addresses?',opts:['NTP','DNS','DHCP','SNMP'],a:1,e:'DNS performs name resolution.'}},
 {id:'s2',domain:'services',title:'NAT & PAT',mins:24,body:`<p>NAT translates IP addresses. PAT, often called NAT overload, lets many inside hosts share one or a small number of public IPv4 addresses by also tracking transport-layer port numbers.</p><p>Learn the inside-local / inside-global terminology, then practice reading translations instead of memorizing words in isolation.</p>`,q:{q:'What allows many private hosts to share one public IPv4 address?',opts:['STP','PAT','OSPF','CDP'],a:1,e:'PAT differentiates translations using Layer 4 port numbers.'}},
 {id:'s3',domain:'services',title:'SSH, Syslog, SNMP & QoS',mins:28,body:`<p>Operational networks need secure administration and visibility. SSH provides encrypted remote CLI access. Syslog carries event messages. SNMP supports monitoring/management. QoS influences how traffic is treated under congestion.</p><h3>QoS verbs</h3><p>Classification identifies traffic; marking labels it; queuing schedules it; policing can drop/remark excess traffic; shaping buffers excess traffic to smooth transmission.</p>`,q:{q:'Which protocol is preferred over Telnet for secure remote CLI access?',opts:['FTP','SSH','TFTP','SNMP'],a:1,e:'SSH encrypts the management session.'}},
 {id:'sec1',domain:'security',title:'Security Thinking: Threat, Vulnerability, Exploit',mins:20,body:`<p>A <b>threat</b> could cause harm. A <b>vulnerability</b> is a weakness. An <b>exploit</b> is a method of taking advantage of a weakness. A mitigation reduces likelihood or impact.</p><p>Good networking security is layered: physical security, secure management, least privilege, segmentation, filtering, endpoint controls, monitoring and user awareness.</p>`,q:{q:'A weakness that an attacker could take advantage of is a...',opts:['Vulnerability','Route','Trunk','Mitigation'],a:0,e:'A vulnerability is a weakness; an exploit uses it.'}},
 {id:'sec2',domain:'security',title:'ACLs: Traffic Rules on Routers',mins:30,lab:'l5',body:`<p>An IPv4 ACL is an ordered list of permit/deny statements. The router checks entries top-down and stops on the first match. There is an implicit deny at the end.</p><h3>Standard vs extended</h3><p>Standard ACLs primarily match source IPv4 address. Extended ACLs can match source, destination, protocol and Layer 4 ports.</p><div class="warning">A correct ACL placed in the wrong direction or on the wrong interface can break traffic. Configuration and placement are separate skills.</div>`,q:{q:'What happens if no ACL entry matches a packet?',opts:['It is permitted','It is denied by the implicit deny','It is sent to the CPU','It is broadcast'],a:1,e:'Every ACL has an implicit deny at the end.'}},
 {id:'sec3',domain:'security',title:'Layer 2 Security & Device Hardening',mins:28,body:`<p>Port security can restrict which MAC addresses use a switchport. DHCP snooping helps distinguish trusted DHCP server-facing ports from untrusted access ports. Dynamic ARP Inspection can validate ARP information using trusted bindings.</p><p>For device hardening, use secure passwords/secrets, SSH rather than Telnet, appropriate privilege, disabled unused services/ports, banners/policies where required, and authenticated management.</p>`,q:{q:'Which feature can restrict allowed MAC addresses on a switch access port?',opts:['Port security','OSPF','NAT','NTP'],a:0,e:'Port security controls MAC address use on switchports.'}},
 {id:'auto1',domain:'auto',title:'Why Networks Are Becoming Programmable',mins:22,body:`<p>Traditional CLI configuration is still essential, but automation improves repeatability and scale. Controller-based networking centralizes parts of control and policy while devices continue forwarding traffic.</p><h3>Planes</h3><p>The <b>data plane</b> forwards traffic. The <b>control plane</b> builds forwarding knowledge. The <b>management plane</b> is how operators and systems configure/observe devices.</p>`,q:{q:'Which plane actually forwards user traffic?',opts:['Data plane','Control plane','Management plane','Application plane'],a:0,e:'The data plane performs forwarding.'}},
 {id:'auto2',domain:'auto',title:'REST APIs & JSON for Networkers',mins:25,body:`<p>An API lets software interact with another system in a defined way. REST-style APIs commonly use HTTP methods: GET to retrieve, POST to create/action, PUT/PATCH to update, and DELETE to remove.</p><h3>JSON</h3><p>JSON represents structured data using objects, arrays, keys and values. Example: <code>{"hostname":"R1","enabled":true}</code>.</p>`,q:{q:'Which HTTP method is commonly used to retrieve a resource?',opts:['GET','DELETE','PATCH','POST'],a:0,e:'GET is commonly used to retrieve/read a resource.'}}
];

const labs={
 l1:{title:'Lab 1 — Your First Cisco Switch',device:'SW1',goals:['Enter privileged EXEC mode','Enter global configuration mode','Set hostname to SW1','Exit to privileged mode','Run show running-config'],hints:['enable','configure terminal','hostname SW1','end','show running-config']},
 l2:{title:'Lab 2 — Build Two VLANs',device:'SW1',goals:['Enter global configuration','Create VLAN 10','Name VLAN 10 USERS','Create VLAN 20','Name VLAN 20 VOICE','Verify with show vlan brief'],hints:['conf t','vlan 10','name USERS','vlan 20','name VOICE','end then show vlan brief']},
 l3:{title:'Lab 3 — Configure a Static Route',device:'R1',goals:['Enter global configuration','Configure 10.20.0.0/16 via 192.168.1.2','Exit configuration','Verify the route table'],hints:['conf t','ip route 10.20.0.0 255.255.0.0 192.168.1.2','end','show ip route']},
 l4:{title:'Lab 4 — Single-Area OSPF',device:'R1',goals:['Enter global configuration','Start OSPF process 1','Set router-id to 1.1.1.1','Advertise 10.0.0.0/24 in area 0','Verify OSPF'],hints:['conf t','router ospf 1','router-id 1.1.1.1','network 10.0.0.0 0.0.0.255 area 0','end then show ip ospf']},
 l5:{title:'Lab 5 — Standard ACL',device:'R1',goals:['Enter global configuration','Create standard ACL 10 permitting 192.168.10.0/24','Exit configuration','Verify ACL'],hints:['conf t','access-list 10 permit 192.168.10.0 0.0.0.255','end','show access-lists']}
};

const quizBank=lessons.map(l=>({...l.q,lesson:l.title,domain:l.domain}));
let state=JSON.parse(localStorage.getItem('ccnaLaunchpad')||'null')||{done:[],quizCorrect:0,quizTotal:0,last:new Date().toDateString()};
let currentView='dashboard', currentLesson=null, quizIndex=0, quizScore=0;
const content=document.querySelector('#content');
const pageTitle=document.querySelector('#pageTitle');
function save(){localStorage.setItem('ccnaLaunchpad',JSON.stringify(state))}
function pct(){return Math.round(state.done.length/lessons.length*100)}
function domainPct(id){let ls=lessons.filter(x=>x.domain===id); return Math.round(ls.filter(x=>state.done.includes(x.id)).length/ls.length*100)}
function setView(v){currentView=v;currentLesson=null;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}

document.querySelector('#nav').onclick=e=>{let b=e.target.closest('.nav-btn');if(b)setView(b.dataset.view)};
document.querySelector('#resetProgress').onclick=()=>{if(confirm('Reset all CCNA Launchpad progress?')){localStorage.removeItem('ccnaLaunchpad');location.reload()}};

function render(){
 if(currentView==='dashboard')renderDashboard();
 if(currentView==='learn') currentLesson?renderLesson(currentLesson):renderLearn();
 if(currentView==='labs')renderLabs();
 if(currentView==='practice')renderPractice();
 if(currentView==='roadmap')renderRoadmap();
}
function renderDashboard(){
 pageTitle.textContent='Your Network Engineering Launchpad';
 content.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="pill">NO EXPERIENCE REQUIRED</span><h2>Learn networking by building it.</h2><p>Short explanations, mental models, Cisco-style CLI practice and troubleshooting. Your goal is not to memorize networking vocabulary — it is to be able to explain, configure, verify and fix a network.</p><div class="cta-row"><button class="btn btn-primary" id="continueBtn">${state.done.length?'Continue learning':'Start from zero'}</button><button class="btn btn-secondary" id="labBtn">Open CLI lab</button></div></div><div class="stat-orbit"><div class="ring" style="--progress:${pct()}%"><div class="ring-inner"><b>${pct()}%</b><small>lessons mastered</small></div></div></div></div></section>
 <div class="section-head"><div><h3>Your training signal</h3><p>What matters is retained skill, not hours watched.</p></div></div>
 <div class="grid grid-3"><div class="card metric"><b>${state.done.length}/${lessons.length}</b><small>lessons mastered</small></div><div class="card metric"><b>${state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100):0}%</b><small>knowledge-check accuracy</small></div><div class="card metric"><b>${Object.keys(labs).length}</b><small>guided CLI labs</small></div></div>
 <div class="section-head"><div><h3>CCNA skill map</h3><p>Built around the current 200-301 exam domains.</p></div><button class="btn btn-secondary" id="allLessons">View course</button></div>
 <div class="grid grid-3">${domains.map(d=>domainCard(d)).join('')}</div>`;
 document.querySelector('#continueBtn').onclick=()=>{setView('learn')};
 document.querySelector('#labBtn').onclick=()=>setView('labs'); document.querySelector('#allLessons').onclick=()=>setView('learn');
 document.querySelectorAll('.domain-card').forEach(x=>x.onclick=()=>{currentView='learn';renderLearn(x.dataset.domain)});
}
function domainCard(d){let dp=domainPct(d.id);return `<div class="card domain-card" data-domain="${d.id}"><div class="domain-icon">${d.icon}</div><h4>${d.title}</h4><p>${d.desc}</p><div class="progress-track"><div class="progress-fill" style="width:${dp}%"></div></div><div class="domain-meta"><span>${lessons.filter(x=>x.domain===d.id).length} lessons</span><span>${dp}%</span></div></div>`}
function nextCourseStep(){
 for(const lesson of lessons){
  if(!state.done.includes(lesson.id))return {lesson};
  if(lesson.lab && !state.labsDone?.includes(lesson.lab) && (!labs[lesson.lab].prereq || state.done.includes(labs[lesson.lab].prereq)))return {lesson,labId:lesson.lab};
 }
 return null;
}
function launchLab(id){currentView='labs';currentLesson=null;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='labs'));renderLabs(id);window.scrollTo(0,0)}
function renderLearn(filter=null,completedId=null){
 currentView='learn';currentLesson=null;pageTitle.textContent='Guided CCNA Course';
 document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='learn'));
 const completed=lessons.find(l=>l.id===completedId);
 const pendingLab=completed?.lab && !state.labsDone?.includes(completed.lab)?completed.lab:null;
 const step=pendingLab?{lesson:completed,labId:pendingLab}:nextCourseStep();
 const ds=filter?domains.filter(d=>d.id===filter):domains;
 content.innerHTML=`<section class="card next-step" aria-labelledby="nextStepTitle"><p role="status">${completed?(pendingLab?'Lesson complete — now apply it in the lab':'Lesson mastery saved. Choose your next step.'):'Your next recommended step'}</p>
<h2 id="nextStepTitle" tabindex="-1">${step?(step.labId?labs[step.labId].title:step.lesson.title):'All lessons and labs complete'}</h2>
${step?`<button class="btn btn-primary" id="nextCourseStep">${step.labId?'Launch required lab':'Open next recommended lesson'}</button>`:'<p>Reopen any lesson or lab to keep practicing.</p>'}</section>
<div class="warning"><b>How to use this course:</b> Check your understanding, then mark the lesson mastered to save your reading progress. Complete its required lab next. Lesson mastery and lab completion are saved separately; review is always available.</div>
${ds.map(d=>`<div class="section-head"><div><h3>${d.icon} ${d.title}</h3><p>${d.desc}</p></div><span class="pill">${domainPct(d.id)}% lessons mastered</span></div>
<div class="module-list">${lessons.filter(l=>l.domain===d.id).map((l,i)=>`<button type="button" class="module ${step?.lesson.id===l.id?'recommended':''}" data-id="${l.id}"><span class="module-num">${i+1}</span><span><strong>${l.title}</strong><span class="module-detail">${state.done.includes(l.id)?'✓ Mastered · Reopen for review':l.mins+' min lesson'}${l.lab?(state.labsDone?.includes(l.lab)?' · Lab complete':' · Required lab pending'):''}</span></span><span class="badge ${l.lab?'lab':''}">${step?.lesson.id===l.id?'NEXT':l.lab?'LAB':'LESSON'}</span></button>`).join('')}</div>`).join('')}`;
 document.querySelectorAll('.module').forEach(x=>x.onclick=()=>{currentLesson=x.dataset.id;render();window.scrollTo(0,0)});
 if(step)document.querySelector('#nextCourseStep').onclick=()=>{if(step.labId)launchLab(step.labId);else{currentLesson=step.lesson.id;render();window.scrollTo(0,0)}};
 if(completedId){window.scrollTo(0,0);document.querySelector('#nextStepTitle').focus({preventScroll:true})}
}
function renderLesson(id){
 const l=lessons.find(x=>x.id===id), d=domains.find(x=>x.id===l.domain); pageTitle.textContent=l.title;
 content.innerHTML=`<div class="lesson-layout"><article class="card lesson-card"><span class="pill">${d.title.toUpperCase()}</span><h2>${l.title}</h2><p class="q-meta">~${l.mins} minutes • beginner explanation • exam-relevant</p>${l.body}<h3>Check yourself</h3><div class="check" id="lessonCheck"><b>${l.q.q}</b>${l.q.opts.map((o,i)=>`<label><input type="radio" name="q" value="${i}"> ${o}</label>`).join('')}<button class="btn btn-secondary" id="checkAnswer">Check answer</button><div class="result" id="result"></div></div></article><aside class="card lesson-nav"><h4>Skill completion</h4><p class="q-meta">Don't mark this complete until you can explain the main idea without reading.</p>${l.lab?`<button class="btn btn-secondary" id="openLessonLab">⌨️ Run associated lab</button>`:''}<button class="btn btn-primary" id="markDone">${state.done.includes(l.id)?'✓ Mastered — return to course':'Mark lesson mastered'}</button><button class="btn btn-secondary" id="backCourse">Back to course</button></aside></div>`;
 document.querySelector('#checkAnswer').onclick=()=>{let r=document.querySelector('input[name=q]:checked');if(!r)return;let ok=+r.value===l.q.a;state.quizTotal++;if(ok)state.quizCorrect++;save();document.querySelector('#result').innerHTML=`<span class="${ok?'ok':'bad'}">${ok?'Correct.':'Not yet.'}</span> ${l.q.e}`};
 document.querySelector('#markDone').onclick=()=>{if(!state.done.includes(l.id))state.done.push(l.id);save();renderLearn(null,id)};
 document.querySelector('#backCourse').onclick=()=>{currentLesson=null;renderLearn()};
 if(l.lab)document.querySelector('#openLessonLab').onclick=()=>{launchLab(l.lab)};
}
function renderLabs(selected='l1'){
 pageTitle.textContent='Cisco CLI Practice Lab';
 const lab=labs[selected]||labs.l1;
 content.innerHTML=`<div class="section-head"><div><h3>${lab.title}</h3><p>Safe simulator: type Cisco-style commands and build the configuration yourself.</p></div><select id="labSelect" class="btn btn-secondary">${Object.entries(labs).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${v.title}</option>`).join('')}</select></div><div class="terminal-wrap"><div class="terminal"><div class="terminal-head">CCNA Launchpad IOS Simulator • ${lab.device}</div><div class="term-output" id="termOut">${lab.device}>Welcome. Type ? for starter help.\n</div><div class="term-input-row"><span class="prompt" id="prompt">${lab.device}&gt;</span><input class="term-input" id="termInput" autofocus autocomplete="off" spellcheck="false"></div></div><div class="card"><h4>Mission checklist</h4><div class="task-list" id="tasks">${lab.goals.map((g,i)=>`<div class="task" data-task="${i}"><b>${i+1}. ${g}</b><p class="hint">Hint: ${lab.hints[i]}</p></div>`).join('')}</div><div id="labDone"></div><h4 style="margin-top:20px">Why this matters</h4><p class="q-meta">The exam expects you to configure and verify, not only recognize commands. Type them. Make mistakes. Read the output.</p><button class="btn btn-secondary" id="resetLab">Reset this lab</button></div></div>`;
 document.querySelector('#labSelect').onchange=e=>renderLabs(e.target.value); document.querySelector('#resetLab').onclick=()=>renderLabs(selected); initTerminal(selected);
}
function initTerminal(labId){
 let mode='user',host=labs[labId].device,vlan=null,ospf=false,progress=new Set(),vlans={},routes=[],acl=[],routerId='',network='';
 const out=document.querySelector('#termOut'),inp=document.querySelector('#termInput'),pr=document.querySelector('#prompt');
 const prompt=()=>mode==='user'?`${host}>`:mode==='priv'?`${host}#`:mode==='config'?`${host}(config)#`:mode==='vlan'?`${host}(config-vlan)#`:mode==='router'?`${host}(config-router)#`:`${host}#`;
 function print(s=''){out.textContent+=s+'\n';out.scrollTop=out.scrollHeight}
 function sync(){pr.textContent=prompt(); document.querySelectorAll('.task').forEach((t,i)=>t.classList.toggle('done',progress.has(i)));if(progress.size===labs[labId].goals.length){state.labsDone=state.labsDone||[];if(!state.labsDone.includes(labId)){state.labsDone.push(labId);save()}document.querySelector('#labDone').innerHTML='<div class="lab-success" role="status"><b>Lab complete.</b> You configured and verified the target state.<br><button class="btn btn-primary" id="labBackCourse">Back to course — next step</button></div>';document.querySelector('#labBackCourse').onclick=()=>setView('learn')}}
 function run(raw){let c=raw.trim(),lc=c.toLowerCase();print(prompt()+c); if(!c)return;
   if(lc==='?'||lc==='help'){print('Starter commands: enable, configure terminal, show running-config, show vlan brief, show ip route, show ip ospf, show access-lists');return}
   if(mode==='user'&&lc==='enable'){mode='priv'; if(labId==='l1')progress.add(0);sync();return}
   if(mode==='user'){print('% Invalid command in user EXEC. Try: enable');return}
   if(lc==='disable'){mode='user';sync();return}
   if((lc==='configure terminal'||lc==='conf t')&&mode==='priv'){mode='config'; if(['l1','l2','l3','l4','l5'].includes(labId))progress.add(labId==='l1'?1:0);sync();return}
   if(lc==='end'){mode='priv'; if(labId==='l1')progress.add(3); if(labId==='l3')progress.add(2); if(labId==='l5')progress.add(2);sync();return}
   if(lc==='exit'){if(mode==='vlan'||mode==='router')mode='config';else if(mode==='config')mode='priv';sync();return}
   if(mode==='config'&&lc.startsWith('hostname ')){host=c.split(/\s+/)[1]||host;if(labId==='l1'&&host.toUpperCase()==='SW1')progress.add(2);sync();return}
   if(mode==='config'&&/^vlan \d+$/i.test(c)){vlan=c.split(/\s+/)[1];vlans[vlan]=vlans[vlan]||'VLAN'+String(vlan).padStart(4,'0');mode='vlan';if(labId==='l2'&&vlan==='10')progress.add(1);if(labId==='l2'&&vlan==='20')progress.add(3);sync();return}
   if(mode==='vlan'&&lc.startsWith('name ')){let name=c.slice(5).trim().toUpperCase();vlans[vlan]=name;if(labId==='l2'&&vlan==='10'&&name==='USERS')progress.add(2);if(labId==='l2'&&vlan==='20'&&name==='VOICE')progress.add(4);sync();return}
   if(mode==='config'&&lc.startsWith('ip route ')){routes.push(c.slice(9));if(labId==='l3'&&lc==='ip route 10.20.0.0 255.255.0.0 192.168.1.2')progress.add(1);sync();return}
   if(mode==='config'&&lc==='router ospf 1'){ospf=true;mode='router';if(labId==='l4')progress.add(1);sync();return}
   if(mode==='router'&&lc==='router-id 1.1.1.1'){routerId='1.1.1.1';if(labId==='l4')progress.add(2);sync();return}
   if(mode==='router'&&lc==='network 10.0.0.0 0.0.0.255 area 0'){network=lc;if(labId==='l4')progress.add(3);sync();return}
   if(mode==='config'&&lc==='access-list 10 permit 192.168.10.0 0.0.0.255'){acl.push('Standard IP access list 10\n    10 permit 192.168.10.0, wildcard bits 0.0.0.255');if(labId==='l5')progress.add(1);sync();return}
   if(mode==='priv'&&lc==='show running-config'){print(`Building configuration...\nhostname ${host}${Object.keys(vlans).map(v=>`\nvlan ${v}\n name ${vlans[v]}`).join('')}${routes.map(r=>`\nip route ${r}`).join('')}${ospf?`\nrouter ospf 1${routerId?`\n router-id ${routerId}`:''}${network?'\n network 10.0.0.0 0.0.0.255 area 0':''}`:''}${acl.length?'\naccess-list 10 permit 192.168.10.0 0.0.0.255':''}`);if(labId==='l1')progress.add(4);sync();return}
   if(mode==='priv'&&lc==='show vlan brief'){print('VLAN Name                             Status\n---- -------------------------------- ---------\n1    default                          active'+Object.keys(vlans).map(v=>`\n${v.padEnd(4)} ${vlans[v].padEnd(32)} active`).join(''));if(labId==='l2'&&vlans['10']==='USERS'&&vlans['20']==='VOICE')progress.add(5);sync();return}
   if(mode==='priv'&&lc==='show ip route'){print('Codes: C - connected, S - static, O - OSPF\nGateway of last resort is not set'+routes.map(r=>`\nS    ${r.split(' ')[0]}/16 [1/0] via ${r.split(' ')[2]}`).join(''));if(labId==='l3'&&routes.length)progress.add(3);sync();return}
   if(mode==='priv'&&lc==='show ip ospf'){print(ospf?`Routing Process "ospf 1" with ID ${routerId||'0.0.0.0'}\n Area BACKBONE(0)`:'% OSPF not configured');if(labId==='l4'&&ospf&&routerId&&network)progress.add(4);sync();return}
   if(mode==='priv'&&lc==='show access-lists'){print(acl.length?acl.join('\n'):'No access lists configured');if(labId==='l5'&&acl.length)progress.add(3);sync();return}
   print('% Invalid input detected. Check mode and syntax.');
 }
 inp.onkeydown=e=>{if(e.key==='Enter'){run(inp.value);inp.value=''}};sync();
}
function renderPractice(){
 pageTitle.textContent='Mixed CCNA Practice';quizIndex=0;quizScore=0;showQuiz();
}
function showQuiz(){let q=quizBank[(quizIndex*7+3)%quizBank.length];content.innerHTML=`<div class="card quiz-card"><div class="q-meta">Question ${quizIndex+1} of 10 • ${domains.find(d=>d.id===q.domain).title}</div><h2>${q.q}</h2><div class="quiz-options">${q.opts.map((o,i)=>`<button class="quiz-option" data-i="${i}">${o}</button>`).join('')}</div><div id="quizExplain"></div></div>`;document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>answerQuiz(b,q));}
function answerQuiz(btn,q){if(document.querySelector('.quiz-option.correct,.quiz-option.wrong'))return;let i=+btn.dataset.i,ok=i===q.a;if(ok)quizScore++;state.quizTotal++;if(ok)state.quizCorrect++;save();document.querySelectorAll('.quiz-option').forEach((b,j)=>{if(j===q.a)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});document.querySelector('#quizExplain').innerHTML=`<div class="explain"><b>${ok?'Correct':'Review this one'}.</b> ${q.e}<br><small>Source lesson: ${q.lesson}</small><br><button class="btn btn-primary" id="nextQuiz" style="margin-top:10px">${quizIndex===9?'See result':'Next question'}</button></div>`;document.querySelector('#nextQuiz').onclick=()=>{quizIndex++;if(quizIndex>=10)showQuizResult();else showQuiz()}}
function showQuizResult(){content.innerHTML=`<div class="card quiz-card"><span class="pill">PRACTICE COMPLETE</span><h2>${quizScore}/10</h2><p>${quizScore>=8?'Strong result. Revisit any miss and explain why the correct answer wins.':quizScore>=6?'You are building the foundation. Review the missed source lessons before another attempt.':'Slow down and return to the guided lessons. Recognition without understanding will not survive troubleshooting questions.'}</p><button class="btn btn-primary" id="again">Practice again</button></div>`;document.querySelector('#again').onclick=renderPractice}
function renderRoadmap(){pageTitle.textContent='From Zero to CCNA';content.innerHTML=`<div class="hero"><span class="pill">12-WEEK DEFAULT PATH</span><h2>A career-building route, not a cram plan.</h2><p>If you study about 60–90 focused minutes on most days, use this as a sequence rather than a deadline. Extend it when life gets busy; do not skip labs to protect a calendar date.</p></div><div class="section-head"><div><h3>Training roadmap</h3><p>Each phase adds one new layer while recycling old skills.</p></div></div><div class="roadmap">${[
 ['Weeks 1–2','Foundations','Networks, OSI/TCP-IP, Ethernet, MAC, ARP, IPv4, subnetting, TCP/UDP. Goal: explain packet delivery on a simple LAN.'],
 ['Weeks 3–4','Switching','Cisco IOS, VLANs, trunks, STP, EtherChannel, CDP/LLDP, wireless basics. Goal: build and verify a small switched campus.'],
 ['Weeks 5–6','Routing','Router interfaces, routing table logic, static/default routes, IPv6 and single-area OSPF. Goal: make multiple networks communicate.'],
 ['Weeks 7–8','Services','DHCP/relay, DNS, NAT/PAT, NTP, SSH, SNMP, syslog and QoS. Goal: make the network useful and manageable.'],
 ['Weeks 9–10','Security','Threats, device hardening, ACLs, port security, DHCP snooping, DAI, AAA, VPN and wireless security. Goal: secure what you built.'],
 ['Week 11','Automation','Controllers, SDN, REST APIs, JSON and configuration management concepts. Goal: understand how modern networks scale.'],
 ['Week 12','Troubleshooting + exam mode','Mixed labs, timed question sets, subnetting drills and weak-area repair. Goal: diagnose before guessing.']
 ].map((s,i)=>`<div class="road-step"><div class="road-dot">${i+1}</div><div class="road-body"><span class="pill">${s[0]}</span><h4>${s[1]}</h4><p>${s[2]}</p></div></div>`).join('')}</div><div class="warning"><b>Career note:</b> CCNA is a foundation, not a job guarantee. Pair the certificate with a small portfolio: topology diagrams, documented labs, troubleshooting notes, and a GitHub repository of sanitized configurations/automation experiments.</div>`}
render();
