// v1.2.0: first complete foundations workshop; independent from brief CCNA topic summaries.
const foundationUnits = [
 {id:'journey',title:'Follow an application request',outcome:'Explain which jobs belong to DNS, switching, routing, and the application.',
  story:'A coworker says, “The scheduling app is down.” Before deciding who to call, build a picture of the systems involved.',
  body:'<h3>One request, several different jobs</h3><p>A client is a device or program requesting a service. A server provides that service. The network carries messages between them; the application decides what those messages mean. A working network does not guarantee a working login, database, or application.</p><p>Suppose your laptop is <code>192.168.10.25/24</code> and you open <code>https://schedule.example.test</code>. In this fictional lab, DNS returns <code>10.20.0.50</code>. DNS is a directory: it translates the name into an address. It does not carry the rest of the application conversation.</p><h3>Decide whether the destination is local</h3><p>The laptop uses its subnet mask with the destination IP address to decide whether to send directly on its local subnet or use a router. With a /24, this laptop’s local network is <code>192.168.10.0/24</code>. The server is outside that subnet, so the laptop sends toward its default gateway, <code>192.168.10.1</code>.</p><p>On an ordinary Ethernet LAN, ARP discovers the MAC address of a local IPv4 neighbor when it is not already cached. For this remote server, the laptop needs the gateway’s MAC address, not the remote server’s MAC address. A MAC address identifies the local Ethernet destination; an IP address identifies the IP destination.</p><h3>Keep the layers separate</h3><p>The Ethernet frame goes through a switch toward the gateway. The router examines the packet’s destination IP and selects a route. At each routed Ethernet hop, new link-layer addressing is used. In this simple example without NAT, the destination IP remains the server’s IP even though the local destination MAC is the gateway’s.</p><p>For this example, HTTPS uses TCP and TLS before the application exchange. TCP manages an ordered transport conversation; TLS helps protect the connection and authenticate the server. These are different jobs from name resolution or choosing a route. Some modern HTTP traffic uses QUIC over UDP instead; this example intentionally follows the TCP case.</p><div class="concept-box"><b>Explain it to a coworker:</b> “The directory finds the address, the network carries the request, and the application handles it. We need evidence to find which part failed.”</div><h3>Worked example: a nearby printer</h3><p>The same laptop sends to <code>192.168.10.80</code>. Both addresses are in the same /24. It normally uses ARP for the printer’s MAC and sends through the local switch. The default gateway is not needed for that local delivery. Being connected to the same physical switch alone does not prove two devices share a subnet or VLAN.</p>',
  guided:{prompt:'A laptop at 192.168.10.25/24 sends to 10.20.0.50 through gateway 192.168.10.1. Which IP stays as the packet destination, and whose MAC is needed for the first Ethernet hop?',
   hint:'Separate the final IP destination from the next local Ethernet destination.',
   answer:'The destination IP is 10.20.0.50. The laptop needs the gateway’s MAC address for the first hop. It does not replace the packet’s destination IP with 192.168.10.1.'},
  reflection:'Explain why knowing a server’s IP address does not prove that its application is working.'},
 {id:'settings',title:'Read a computer’s network settings',outcome:'Interpret an address, mask, gateway, DNS server, and DHCP setting without treating them as interchangeable.',
  story:'IT asks you for the affected computer’s network configuration. A screenshot is more useful when you can explain what its fields mean.',
  body:'<h3>Read the fields as a set</h3><p>An IPv4 address has four octets, each from 0 to 255. The subnet mask separates the network portion from the host portion. A prefix such as /24 counts the network bits; /24 is equivalent to <code>255.255.255.0</code>. The address alone cannot tell you which destinations are local.</p><pre class="sample-output">Fictional client configuration\nIPv4 address:     192.168.40.23\nSubnet mask:      255.255.255.0\nDefault gateway:  192.168.40.1\nDNS server:       10.50.0.53\nDHCP enabled:     Yes</pre><p>The address identifies this interface. The mask makes its local subnet <code>192.168.40.0/24</code>. The gateway is the next router for destinations outside that subnet. The DNS server answers name-resolution questions and can be on a different subnet; reaching this DNS server requires routing.</p><h3>Assignment and use are different</h3><p>DHCP can lease an address and provide options such as the mask, gateway, and DNS server. DHCP is not the service that translates application names. A manually configured address can work too, but the values must fit the network’s plan and must not duplicate another device’s address.</p><p>On a typical /24, the network address ends in .0 and the broadcast address in .255. Normal host addresses are .1 through .254. The gateway is often .1, but that is an administrator’s choice, not a universal rule. Later you will see subnets whose boundaries are not .0 and .255.</p><h3>Worked example: a suspicious gateway</h3><p>If this client is configured with gateway <code>192.168.41.1</code>, it is outside the client’s /24. In this ordinary Ethernet setup, that is inconsistent with the expected local next hop. Compare the approved addressing plan and a working peer before changing anything. Do not simply assume every gateway must end in .1.</p><p>A local peer may still be reachable while a remote service fails, because local delivery does not require that gateway. Conversely, a DNS failure can stop access by name while some address-based communication works.</p><h3>Gather evidence before making changes</h3><p>On Windows, <code>ipconfig /all</code> displays detailed adapter information. Inspect the adapter actually carrying the connection; a computer may also have VPN and virtual adapters. Record the relevant address, mask, gateway, DNS servers, and DHCP status. This workshop uses fictional output; it does not inspect your device.</p><p>An automatically assigned <code>169.254.x.x</code> address can be a clue that normal DHCP configuration was not obtained. It is a starting hypothesis, not enough evidence to declare that the DHCP server itself is broken.</p>',
  guided:{prompt:'For 192.168.40.23/24, is 192.168.40.200 local? Is 10.50.0.53 local? Which setting helps reach the remote address?',
   hint:'A /24 fixes the first three octets as the network portion in this example.',
   answer:'192.168.40.200 is local. 10.50.0.53 is remote. The client uses its default gateway for that remote destination. DNS being remote is not inherently a configuration error.'},
  reflection:'Describe the difference between DHCP, DNS, and the default gateway using this client’s settings.'},
 {id:'subnets',title:'Calculate subnet boundaries',outcome:'Find the network, broadcast, usable range, and host count for common /24–/29 subnets.',
  story:'A team needs a separate small network for devices. You need to check whether the proposed addresses actually belong together.',
  body:'<h3>Start with bits, then use a repeatable method</h3><p>IPv4 has 32 bits: four octets of eight bits. An octet’s bit values are 128, 64, 32, 16, 8, 4, 2, and 1. A /26 reserves 26 bits for the network and leaves 6 host bits. Its mask ends with binary <code>11000000</code>, which is 128 + 64 = 192: <code>255.255.255.192</code>.</p><p>Six host bits produce <code>2^6 = 64</code> total addresses in each /26 block. In the ordinary multiaccess subnets used here, subtract the network and broadcast addresses to get 62 usable host addresses. /31 point-to-point links and /32 host routes have different uses; do not apply “minus two” blindly to every prefix.</p><div class="concept-box"><b>Last-octet block sizes:</b> /24 → 256; /25 → 128; /26 → 64; /27 → 32; /28 → 16; /29 → 8. A longer prefix leaves fewer host bits and makes smaller subnets.</div><h3>Worked example: 192.168.10.77/26</h3><ol><li>The block size is 64. Boundaries in the last octet are 0, 64, 128, and 192.</li><li>77 belongs to the block beginning at 64, so the network is <code>192.168.10.64</code>.</li><li>The next block begins at 128. One less is 127, so broadcast is <code>192.168.10.127</code>.</li><li>First usable is <code>192.168.10.65</code>; last usable is <code>192.168.10.126</code>.</li><li>The subnet has 64 total addresses and 62 usable hosts.</li></ol><p>The general shortcut for these last-octet examples is: divide the address’s last octet by the block size, round down, and multiply by the block size. Add block size minus one for broadcast. This shortcut is scoped to /24 through /29 here; shorter prefixes require boundaries in earlier octets.</p><h3>Use the answer to make a decision</h3><p><code>192.168.10.100</code> is in that /26; <code>192.168.10.130</code> is not. Sharing the first three octets does not make addresses local when the prefix is longer than /24.</p><p>A request for 20 usable addresses needs at least a /27 among these conventional subnet sizes: /28 offers only 14 usable addresses, while /27 offers 30. Real planning must also count infrastructure addresses and allow agreed growth.</p><h3>Check your reasoning</h3><p>Network ≤ host ≤ broadcast must hold. The usable range excludes both boundaries. The number of addresses from network through broadcast must match the block size. Practice with a fresh address after the example; remembering “64 and 127” is not the skill.</p>',
  guided:{prompt:'Find the network, broadcast, usable range, and usable-host count for 192.168.20.50/27. Write your answer before opening the solution.',
   hint:'A /27 has blocks of 32. Which block contains 50?',
   answer:'Network 192.168.20.32; broadcast 192.168.20.63; usable range 192.168.20.33–192.168.20.62; 30 usable hosts. 50 falls between the 32 and 64 boundaries.'},
  reflection:'Describe how you found the block containing the address. Why does subtracting two make sense for these examples?'},
 {id:'triage',title:'Investigate a name-resolution problem',outcome:'Choose a useful next test and distinguish evidence from assumptions when an application fails.',
  story:'One coworker cannot open an internal application by name. Others can. Your job is to gather useful evidence and narrow the problem before escalating.',
  body:'<h3>Define the symptom and its scope</h3><p>Record the exact error, time, affected user/device, and whether other applications work. “The network is down” is a conclusion; “this hostname fails on one wired client while a nearby client works” is an observation. Ask about recent changes without assuming they caused the fault.</p><h3>Compare hypotheses</h3><p>A wrong IP configuration, failed name resolution, blocked transport connection, certificate problem, authentication failure, or unavailable application can all prevent access. Pick a test that separates explanations rather than changing several settings at once.</p><p>A successful ping shows an ICMP response from that address at that time. It does not establish that a web service is healthy. A failed ping does not establish a broken network either; ICMP may be filtered. Likewise, opening an HTTPS service by IP can behave differently because of certificates and virtual hosting. Treat it as limited evidence, not a perfect substitute for testing its name.</p><h3>Worked example: compare resolvers</h3><pre class="sample-output">Fictional approved lab\nAffected client: 192.168.40.23/24\nGateway:        192.168.40.1\nConfigured DNS: 192.168.40.54\nApproved DNS:   192.168.40.53\n\nResolve-DnsName schedule.example.test\nResult: timeout using 192.168.40.54\n\nResolve-DnsName schedule.example.test -Server 192.168.40.53\nResult: 10.20.0.50\n\nWorking peer uses 192.168.40.53 and resolves the name.</pre><p>The different resolver results and configuration mismatch support investigating this client’s DNS configuration or its configured resolver path. They do not prove that the application server is healthy or that every DNS service is down.</p><h3>Act within your role, then verify</h3><p>In a workplace, compare with the approved configuration and ask the responsible IT team to correct the source—such as a DHCP option or a manual override—rather than blindly setting public DNS. Public resolvers may not know internal names. In the simulation below, you make decisions about fictional evidence; no commands run on your computer.</p><p>After an approved correction, test name resolution again and then the actual application by its intended hostname. A successful lookup alone is not the end-to-end verification. Keep the before/after evidence and identify who made the change.</p><h3>Make the escalation useful</h3><p>A useful handoff includes symptom, scope, time, relevant client settings, tests and outputs, the hypothesis those outputs support, and what remains untested. Do not include passwords or private customer data. State uncertainty plainly: “These results suggest a DNS configuration mismatch; application access still needs verification.”</p>',
  guided:{prompt:'The approved resolver returns the expected address, but the application still shows a login error. Is name resolution alone enough to close the incident?',
   hint:'Separate a successful DNS answer from the application’s own response.',
   answer:'No. Name resolution worked in that test. A login error needs investigation at the authentication/application layer, with the network evidence retained. Verify the user’s actual workflow before closing the incident.'},
  reflection:'Write a short handoff: what failed, what you tested, what the evidence suggests, and what still needs checking.'}
];
const foundationDiagnostic = [
 {unit:'journey',q:'A server is outside the client’s local subnet. For the first Ethernet hop, whose MAC address is normally needed?',opts:['The remote server’s','The local default gateway’s','The DNS name’s'],a:1,why:'The frame goes to the local gateway; the packet keeps the remote destination IP in this no-NAT example.'},
 {unit:'settings',q:'Which service can supply an address, subnet mask, gateway, and DNS settings to a client?',opts:['DHCP','DNS','HTTPS'],a:0,why:'DHCP supplies configuration. DNS resolves names; HTTPS serves protected application traffic.'},
 {unit:'subnets',q:'Is 192.168.10.130 in the same /26 as 192.168.10.77?',opts:['Yes, the first three octets match','No, they occupy different /26 blocks','Only if the gateway ends in .1'],a:1,why:'77 belongs to .64–.127; 130 belongs to .128–.191.'},
 {unit:'triage',q:'A ping responds from a server. What does that establish?',opts:['The application login works','All network problems are ruled out','The address responded to ICMP at that time'],a:2,why:'An ICMP response is limited evidence; the application workflow still needs testing.'}
];
const foundationGlossary = [
  ['IP address','An Internet Protocol address used to identify an interface for IP communication.'],
  ['Packet and frame','An IP packet carries IP-layer information. An Ethernet frame wraps data for delivery on a local link. They are different layers of the same communication.'],
  ['MAC address','A link-layer address used for local frame delivery, distinct from an IP address.'],
  ['Subnet and prefix','A subnet is an IP network subdivision. A prefix such as /26 states how many leading address bits identify the network.'],
  ['Default gateway','The local router a host normally uses when a destination is outside its directly connected subnet and no more specific route applies.'],
  ['DNS','Domain Name System: resolves names to information such as IP addresses.'],
  ['DHCP','Dynamic Host Configuration Protocol: can provide address configuration and options to clients.'],
  ['ARP','Address Resolution Protocol: finds the MAC address for a local IPv4 neighbor.'],
  ['TCP and TLS','Transmission Control Protocol provides reliable ordered transport. Transport Layer Security protects a connection and supports server authentication.'],
  ['NAT','Network Address Translation: changes IP addressing information at a translation device. The first request example assumes no NAT.'],
  ['VLAN','Virtual LAN: a separate Layer 2 broadcast domain. Sharing a switch does not guarantee that devices are in the same VLAN.'],
  ['ICMP','Internet Control Message Protocol: carries control and diagnostic messages. Ping commonly uses its echo request and reply messages.']
];
function foundationEscape(value) { return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function normalizeFoundations(raw) {
  const value=raw && typeof raw==='object'?raw:{};
  const ids=foundationUnits.map(u=>u.id);
  return {
    read:Array.isArray(value.read)?[...new Set(value.read.filter(id=>ids.includes(id)))]:[],
    diagnostic:value.diagnostic && Array.isArray(value.diagnostic.correct) && value.diagnostic.correct.length===4 && value.diagnostic.correct.every(x=>typeof x==='boolean')
      ? {correct:value.diagnostic.correct.map(Boolean),at:typeof value.diagnostic.at==='string'?value.diagnostic.at:null}:null,
    notes:Object.fromEntries(ids.filter(id=>typeof value.notes?.[id]==='string').map(id=>[id,value.notes[id].slice(0,3000)])),
    attempts:Array.isArray(value.attempts)?value.attempts.filter(a=>ids.includes(a.unit) && a.version==='1.2.0' && typeof a.correct==='boolean' && typeof a.helpUsed==='boolean')
      .slice(-100).map(a=>({unit:a.unit,version:a.version,correct:a.correct,helpUsed:a.helpUsed,at:typeof a.at==='string'?a.at:null,summary:typeof a.summary==='string'?a.summary.slice(0,500):''})): []
  };
}
function foundationScenario(unit,random=Math.random) {
  const pick=n=>Math.floor(random()*n), octet=10+pick(180), host=20+pick(80);
  if(unit==='subnets'){
    const prefix=24+pick(6),block=2**(32-prefix),start=pick(256/block)*block,ip=start+1+pick(block-2),base='192.168.'+octet+'.';
    return {unit,summary:base+ip+'/'+prefix,prompt:'For '+base+ip+'/'+prefix+', calculate all five values. Use a conventional multiaccess subnet.',
      fields:[['network','Network address',base+start],['broadcast','Broadcast address',base+(start+block-1)],['first','First usable address',base+(start+1)],['last','Last usable address',base+(start+block-2)],['hosts','Usable-host count',String(block-2)]],
      hint:'There are 32 − prefix host bits. The block has 2^(host bits) addresses. Find the block containing the last octet.',
      explain:'Block size '+block+'. The containing block runs from '+start+' through '+(start+block-1)+'. Remove those two boundary addresses for the usable range.'};
  }
  if(unit==='journey')return {unit,summary:'Remote application from 192.168.'+octet+'.'+host+'/24',
    prompt:'A laptop at 192.168.'+octet+'.'+host+'/24 uses gateway 192.168.'+octet+'.1. DNS returns 10.20.0.50 for an application. Assume an ordinary Ethernet LAN and no NAT.',
    fields:[['destination','Packet destination IP','10.20.0.50'],['neighbor','IP of the neighbor whose MAC is needed','192.168.'+octet+'.1']],
    choice:{q:'Which statement best explains the first hop?',opts:['The gateway replaces the destination IP with its own','The frame targets the gateway while the packet targets the server','DNS carries the application packets'],a:1},
    hint:'The packet destination and local frame destination perform different jobs.',
    explain:'The remote server remains the IP destination. The gateway is the local next hop, so the client needs its MAC address.'};
  if(unit==='settings')return {unit,summary:'Client 192.168.'+octet+'.'+host+'/24',
    prompt:'A client has address 192.168.'+octet+'.'+host+', mask 255.255.255.0, gateway 192.168.'+octet+'.1, and DNS server 10.50.0.53. The approved addressing plan matches these settings.',
    fields:[['network','Client’s network address','192.168.'+octet+'.0'],['gateway','Next-hop IP for reaching 10.50.0.53','192.168.'+octet+'.1']],
    choice:{q:'Is a DNS server on a different subnet necessarily a mistake?',opts:['Yes, DNS must be in the client’s subnet','No, it can be reached through routing','Yes, DHCP and DNS must share an address'],a:1},
    hint:'The mask determines local delivery. A service can be on a different network if routing and policy allow access.',
    explain:'The local network is 192.168.'+octet+'.0/24. DNS is remote, so the gateway is the next hop. A remote DNS server is a normal possible design.'};
  const mismatch=pick(2)===0;
  return {unit,summary:mismatch?'DNS configuration mismatch':'DNS succeeds; application reports a login error',
    prompt:mismatch?'One client cannot resolve inventory.example.test. Its configured DNS server is 192.168.60.54; the approved configuration specifies 192.168.60.53. Queries through .54 time out; a direct query to .53 returns the expected address. A working peer uses .53.':'The client resolves inventory.example.test to its expected IP using the approved DNS server. A connection to the HTTPS service succeeds, and the application returns “account locked.”',
    fields:[],
    choice:mismatch?{q:'What is the best-supported next step?',opts:['Declare the application server down','Ask IT to investigate/correct the resolver configuration mismatch, then retest DNS and the application','Switch every computer to public DNS'],a:1}:{q:'What is the best-supported next step?',opts:['Investigate the account/authentication issue with the application team while retaining the successful network tests','Replace the client’s subnet mask','Declare that all DNS servers are broken'],a:0},
    secondChoice:{q:'What should be verified before closing this incident?',opts:['Only a successful ping','Only that a setting was changed','The intended application workflow by its hostname, with before/after evidence'],a:2},
    hint:'Choose the explanation supported by the outputs, and then test the user’s actual workflow.',
    explain:mismatch?'The configuration mismatch and contrasting resolver results support investigating that resolver path. They do not prove the application itself is healthy.':'DNS and service connectivity succeeded in these observations. The explicit account error points toward authentication; it does not justify changing the network mask.'};
}
function gradeFoundation(scenario,answers) {
  const checks=scenario.fields.map(([id,label,expected])=>({label,correct:String(answers[id]||'').trim()===expected,expected}));
  if(scenario.choice)checks.push({label:scenario.choice.q,correct:String(answers.choice)===String(scenario.choice.a),expected:scenario.choice.opts[scenario.choice.a]});
  if(scenario.secondChoice)checks.push({label:scenario.secondChoice.q,correct:String(answers.secondChoice)===String(scenario.secondChoice.a),expected:scenario.secondChoice.opts[scenario.secondChoice.a]});
  return {correct:checks.every(c=>c.correct),checks};
}
let foundationAttempt=null;
function renderFoundations() {
  activate('foundations');currentLesson=null;pageTitle.textContent='Foundations workshop';
  const f=state.foundations, recommended=f.diagnostic?foundationUnits.find((u,i)=>!f.diagnostic.correct[i]):null;
  content.innerHTML='<section class="hero"><span class="pill">MODULE 1 · FROM SYMPTOM TO EVIDENCE</span><h2>Understand the network behind an application.</h2><p>Four connected units for someone who works with IT and wants to understand the mechanisms. Choose a unit that matches what you need to practice.</p><div class="cta-row"><button class="btn btn-primary" id="workshopBegin">'+(recommended?'Start recommended unit':'Start the first unit')+'</button><button class="btn btn-secondary" id="diagnosticStart">'+(f.diagnostic?'Retake starting check':'Find my starting point')+'</button></div></section>'+
    (recommended?'<p class="course-note">Your starting check suggests reviewing <b>'+recommended.title+'</b>. This is a suggestion, not a placement exam.</p>':'')+
    '<div class="section-head"><h3>Learn, work through an example, then try a fresh problem</h3></div><div class="module-list">'+foundationUnits.map((u,i)=>{
      const attempts=f.attempts.filter(a=>a.unit===u.id),last=attempts.at(-1);
      return '<button class="module workshop-unit" data-unit="'+u.id+'"><span class="module-num">'+(i+1)+'</span><span><strong>'+u.title+'</strong><span class="module-detail">'+u.outcome+'</span><span class="module-detail">'+(f.read.includes(u.id)?'Reading recorded':'Reading available')+(last?' · Latest scenario: '+(last.correct?'correct':'needs review')+(last.helpUsed?' with help':' on first submission without the hint'):' · No scenario submitted')+'</span></span></button>';
    }).join('')+'</div><div class="section-head"><h3>Your evidence</h3></div><div class="card"><p>'+f.read.length+' of 4 readings recorded. '+f.attempts.length+' scenario submissions retained. Each result describes that problem only; longer-term retention has not been assessed.</p>'+
    (f.attempts.length?'<ul>'+f.attempts.slice(-8).reverse().map(a=>'<li>'+foundationEscape(foundationUnits.find(u=>u.id===a.unit).title)+': '+foundationEscape(a.summary)+' — '+(a.correct?'correct':'review needed')+(a.helpUsed?' (hint used)':' (no hint used)')+'</li>').join('')+'</ul>':'<p>Your scenario results will appear here.</p>')+
    '<button class="btn btn-secondary" id="exportFoundation">Download my workshop notes</button></div>';
  document.querySelector('#workshopBegin').onclick=()=>renderFoundationUnit(recommended?.id||'journey');
  document.querySelector('#diagnosticStart').onclick=renderFoundationDiagnostic;
  document.querySelectorAll('.workshop-unit').forEach(b=>b.onclick=()=>renderFoundationUnit(b.dataset.unit));
  document.querySelector('#exportFoundation').onclick=exportFoundationNotes;
  window.scrollTo(0,0);
}
function renderFoundationDiagnostic() {
  pageTitle.textContent='Find your starting point';
  content.innerHTML='<div class="card"><h2>A short starting check</h2><p>Answer from memory. These four questions only suggest where to begin; all units remain available.</p><form id="foundationDiagnostic">'+foundationDiagnostic.map((q,i)=>'<fieldset><legend>'+q.q+'</legend>'+q.opts.map((o,j)=>'<label class="answer-line"><input type="radio" name="d'+i+'" value="'+j+'" required> '+o+'</label>').join('')+'</fieldset>').join('')+'<div class="cta-row"><button class="btn btn-primary">Show suggested starting point</button><button type="button" class="btn btn-secondary" id="skipDiagnostic">Skip to units</button></div></form><div id="diagnosticResult" role="status"></div></div>';
  document.querySelector('#skipDiagnostic').onclick=renderFoundations;
  document.querySelector('#foundationDiagnostic').onsubmit=e=>{
    e.preventDefault();const data=new FormData(e.target),correct=foundationDiagnostic.map((q,i)=>Number(data.get('d'+i))===q.a);
    state.foundations.diagnostic={correct,at:new Date().toISOString()};save();
    e.target.querySelectorAll('input,button').forEach(el=>el.disabled=true);
    document.querySelector('#diagnosticResult').innerHTML='<h3>Where to focus</h3>'+foundationDiagnostic.map((q,i)=>'<p><b>'+foundationUnits[i].title+': '+(correct[i]?'this answer was correct':'review recommended')+'.</b> '+q.why+'</p>').join('')+'<button class="btn btn-primary" id="diagnosticContinue">Go to my units</button>';
    document.querySelector('#diagnosticContinue').onclick=renderFoundations;
  };window.scrollTo(0,0);
}
function renderFoundationUnit(id) {
  activate('foundations');const u=foundationUnits.find(u=>u.id===id);pageTitle.textContent=u.title;
  content.innerHTML='<div class="lesson-layout"><article class="card lesson-card"><span class="pill">FOUNDATIONS WORKSHOP</span><h2>'+u.title+'</h2><p><b>After this unit:</b> '+u.outcome+'</p><div class="analogy">'+u.story+'</div><details class="glossary"><summary>Plain-language glossary</summary><dl>'+foundationGlossary.map(([term,definition])=>'<dt><b>'+term+'</b></dt><dd>'+definition+'</dd>').join('')+'</dl></details>'+u.body+
    (id==='journey'?'<h3>Trace the first request</h3><div class="request-path">'+['1 · Resolve the name','2 · Decide local or remote','3 · Reach the gateway','4 · Reach the application'].map((label,i)=>'<button class="btn btn-secondary path-step" data-step="'+i+'" aria-pressed="false">'+label+'</button>').join('')+'</div><p id="pathExplanation" class="concept-box" role="status">Choose a step to inspect its job.</p>':'')+
    '<h3>Guided exercise</h3><p>'+u.guided.prompt+'</p><label for="guidedWork">Work it out in your own words</label><textarea id="guidedWork" rows="4" maxlength="3000" placeholder="Use scratch work; this text is not graded."></textarea><details><summary>Show a hint</summary><p>'+u.guided.hint+'</p></details><details><summary>Compare with the worked solution</summary><p>'+u.guided.answer+'</p></details>'+
    '<h3>Explain the reasoning</h3><p>'+u.reflection+'</p><label for="foundationNote">Your reflection (saved as notes, not automatically graded)</label><textarea id="foundationNote" rows="5" maxlength="3000">'+foundationEscape(state.foundations.notes[id]||'')+'</textarea><button class="btn btn-secondary" id="saveFoundationNote">Save reflection</button><p id="noteStatus" role="status"></p>'+
    '<h3>Reference and further reading</h3><p><a href="https://www.cisco.com/en/US/docs/internetworking/troubleshooting/guide/tr1907.html" target="_blank" rel="noopener">Cisco: troubleshooting TCP/IP</a> · <a href="https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/troubleshoot-dns-client-resolution-issues" target="_blank" rel="noopener">Microsoft: DNS client troubleshooting</a></p></article>'+
    '<aside class="card lesson-nav"><h3>Apply this unit</h3><p>Work through the example, then solve a different scenario. Notes and reading status are self-reported.</p><button class="btn btn-secondary" id="readFoundation">'+(state.foundations.read.includes(id)?'✓ Reading recorded':'Mark this unit read')+'</button><button class="btn btn-primary" id="challengeFoundation">Try a fresh scenario</button><button class="btn btn-secondary" id="backFoundations">Back to workshop</button></aside></div>';
  document.querySelector('#readFoundation').onclick=()=>{if(!state.foundations.read.includes(id))state.foundations.read.push(id);save();document.querySelector('#readFoundation').textContent='✓ Reading recorded';};
  document.querySelector('#saveFoundationNote').onclick=async()=>{const notice=document.querySelector('#noteStatus');state.foundations.notes[id]=document.querySelector('#foundationNote').value;const saved=await save();if(notice.isConnected)notice.textContent=saved?'Reflection saved. It has not been graded.':'Reflection remains in this session; it could not be saved.';};
  function keepDraft(){state.foundations.notes[id]=document.querySelector('#foundationNote').value;save();}
  document.querySelector('#foundationNote').onchange=keepDraft;
  document.querySelector('#challengeFoundation').onclick=()=>{keepDraft();startFoundationScenario(id);};
  document.querySelector('#backFoundations').onclick=()=>{keepDraft();renderFoundations();};
  const explanations=['DNS returns an IP address for the name, or a cached answer may already be available. This step does not test the application itself.','The client compares the destination with its own subnet using the mask. A remote destination needs a router.','ARP identifies the local gateway’s MAC if needed. The Ethernet frame targets that MAC; the packet still targets the remote server.','Routers forward toward the server. In this example, TCP/TLS and then the application exchange follow. A return path is also needed.'];
  document.querySelectorAll('.path-step').forEach(b=>b.onclick=()=>{document.querySelectorAll('.path-step').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#pathExplanation').textContent=explanations[Number(b.dataset.step)];});
  window.scrollTo(0,0);
}
function startFoundationScenario(id) {
  const prior=state.foundations.attempts.filter(a=>a.unit===id).at(-1);
  let scenario=foundationScenario(id);
  for(let retry=0;prior && scenario.summary===prior.summary && retry<10;retry++)scenario=foundationScenario(id);
  if(id==='triage' && prior && scenario.summary===prior.summary)scenario=foundationScenario(id,()=>prior.summary.startsWith('DNS configuration')?0.9:0.1);
  foundationAttempt={scenario,helpUsed:false,submitted:false};
  const s=foundationAttempt.scenario;pageTitle.textContent='Apply: '+foundationUnits.find(u=>u.id===id).title;
  const choice=(q,name)=>q?'<fieldset><legend>'+q.q+'</legend>'+q.opts.map((o,i)=>'<label class="answer-line"><input type="radio" name="'+name+'" value="'+i+'" required> '+o+'</label>').join('')+'</fieldset>':'';
  content.innerHTML='<div class="card scenario-card"><span class="pill">FRESH SCENARIO</span><h2>Solve it before viewing feedback</h2><p>'+s.prompt+'</p><p class="q-meta">First submission only for this scenario. Using the hint is welcome and will label this attempt as helped. After feedback, try a new scenario.</p><form id="foundationScenario">'+
    s.fields.map(([key,label])=>'<label class="scenario-field" for="answer-'+key+'">'+label+'<input id="answer-'+key+'" name="'+key+'" required autocomplete="off" inputmode="'+(key==='hosts'?'numeric':'decimal')+'"></label>').join('')+
    choice(s.choice,'choice')+choice(s.secondChoice,'secondChoice')+'<div class="cta-row"><button class="btn btn-primary" id="submitFoundationScenario">Check my reasoning</button><button type="button" class="btn btn-secondary" id="foundationHint">Show a hint</button></div></form><p id="foundationHintText" role="status"></p><div id="foundationFeedback" role="status"></div><div class="cta-row"><button class="btn btn-secondary" id="returnFoundationUnit">Return to explanation</button><button class="btn btn-secondary" id="scenarioWorkshop">Workshop overview</button></div></div>';
  document.querySelector('#foundationHint').onclick=()=>{foundationAttempt.helpUsed=true;document.querySelector('#foundationHintText').textContent=s.hint+' This attempt will be recorded as helped.';};
  document.querySelector('#foundationScenario').onsubmit=e=>{
    e.preventDefault();if(foundationAttempt.submitted)return;foundationAttempt.submitted=true;
    const answers=Object.fromEntries(new FormData(e.target)),result=gradeFoundation(s,answers);
    state.foundations.attempts.push({unit:id,version:'1.2.0',correct:result.correct,helpUsed:foundationAttempt.helpUsed,at:new Date().toISOString(),summary:s.summary});
    state.foundations.attempts=state.foundations.attempts.slice(-100);save();
    e.target.querySelectorAll('input,button').forEach(el=>el.disabled=true);
    document.querySelector('#foundationFeedback').innerHTML='<h3>'+(result.correct?'All answers correct for this scenario':'Review the reasoning below')+'</h3><p>'+(foundationAttempt.helpUsed?'Recorded as a helped attempt.':'Recorded as a first submission without the in-app hint. This does not establish long-term retention.')+'</p><ul>'+
      result.checks.map(c=>'<li><b>'+(c.correct?'Correct':'Review')+': '+foundationEscape(c.label)+'</b> — '+foundationEscape(c.expected)+'</li>').join('')+'</ul><p>'+s.explain+'</p><button class="btn btn-primary" id="newFoundationScenario">Try a new scenario</button>';
    document.querySelector('#newFoundationScenario').onclick=()=>startFoundationScenario(id);
  };
  document.querySelector('#returnFoundationUnit').onclick=()=>renderFoundationUnit(id);
  document.querySelector('#scenarioWorkshop').onclick=renderFoundations;window.scrollTo(0,0);
}
function exportFoundationNotes() {
  const f=state.foundations;
  const text='# Networking foundations workshop notes\n\nExported '+new Date().toISOString()+'\n\nThese are learner reflections and results on limited scenarios, not a certification or independent skill assessment.\n\n'+
    foundationUnits.map(u=>'## '+u.title+'\n\n'+(f.notes[u.id]||'No reflection recorded.')+'\n\n').join('')+
    '## Scenario records (up to 100 recent submissions)\n\n'+f.attempts.map(a=>a.at+' | '+a.unit+' | '+a.summary+' | '+(a.correct?'correct':'review needed')+' | '+(a.helpUsed?'hint used':'no in-app hint used')).join('\n');
  const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})),link=document.createElement('a');
  link.href=url;link.download='networking-foundations-notes.md';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
